### ISSUE TITLE
Extract code from Tests class to another class

### ISSUE THREAD

**Issue by dmuca** [KrzysztofDzioba/ListInterfaceTesting#1]
https://github.com/KrzysztofDzioba/ListInterfaceTesting/blob/80b215a7e68130be952640278df47a0ca1724ec9/src/test/java/Tests.java#L24

I would suggest to exctract that method to separate class to follow SOLID principles, so u only runs one/two lines of code from Main class. 

I would also suggest to create tree separate methods from code 

1) i.e. runTestMethods()

```
List<Future<?>> futures = new ArrayList<>();
        Method[] myTests = ListTests.class.getMethods();
        Stream.of(myTests)
                .filter(m -> Modifier.isStatic(m.getModifiers()))
                .forEach(s -> {
                    Tests.createEmptyLists();
                    futures.add(runTestInNewThread(s, arrayList));
                    futures.add(runTestInNewThread(s, linkedList));
        });
```

2)  i.e. checkWhetherTestFinished()
```
        int counter = 0;
        for(;;) {
            for(Future<?> future : futures){
                if(!future.isDone())
                    counter ++; // check if future is done
            }
            if(counter == 0)
                break;
            counter = 0;
        }
```

3)  i.e. printMessage()

        System.out.println("Finished all tests");
        System.out.println("Passed tests: " + "\u001B[32m" + passedTests);
        System.out.println("\u001B[0m" + "Failed tests: " + "\u001B[31m" + failedTests);

**Comment by KrzysztofDzioba** [comment]
Ok
